plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'escapeShip.Main'
}

// tag::repositories[]
repositories {
    mavenCentral()
}
// end::repositories[]

// tag::jar[]
jar {
    archiveBaseName = 'escape-ship'
    archiveVersion = '0.1.0'
}
// end::jar[]

// tag::dependencies[]
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    testImplementation "junit:junit:4.12"
}
// end::dependencies[]

// tag::wrapper[]
// end::wrapper[]
